INSERT INTO users (name) Values ("user1");
INSERT INTO users (name) Values ("user2");
INSERT INTO users (name) Values ("user3");
INSERT INTO users (name) Values ("user4");
INSERT INTO users (name) Values ("user5");
INSERT INTO users (name) Values ("user6");
INSERT INTO users (name) Values ("user7");
INSERT INTO users (name) Values ("user8");
INSERT INTO users (name) Values ("user9");
INSERT INTO users (name) Values ("user10");
INSERT INTO users (name) Values ("user11");
INSERT INTO users (name) Values ("user12");
INSERT INTO users (name) Values ("user13");
INSERT INTO users (name) Values ("user14");
INSERT INTO users (name) Values ("user15");
INSERT INTO users (name) Values ("user16");
INSERT INTO users (name) Values ("user17");
INSERT INTO users (name) Values ("user18");
INSERT INTO users (name) Values ("user19");
INSERT INTO users (name) Values ("user20");


INSERT INTO projects (title) Values ("project1");
INSERT INTO projects (title) Values ("project2");
INSERT INTO projects (title) Values ("project3");
INSERT INTO projects (title) Values ("project4");
INSERT INTO projects (title) Values ("project5");
INSERT INTO projects (title) Values ("project6");
INSERT INTO projects (title) Values ("project7");
INSERT INTO projects (title) Values ("project8");
INSERT INTO projects (title) Values ("project9");
INSERT INTO projects (title) Values ("project10");

INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
INSERT INTO pledges (user_id, project_id) Values (1, 1);
